pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/ahmed1707hamed-tech/intelligent-traffic-devops.git'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker build -t traffic-backend ./backend'
                sh 'docker build -t traffic-dashboard ./frontend'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }

    }
}
