apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-backend
  template:
    metadata:
      labels:
        app: traffic-backend
    spec:
      containers:
      - name: traffic-backend
        image: ahmed7amed9/traffic-backend:latest
        ports:
        - containerPort: 5000