apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: traffic-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: traffic-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort